"""update to User ORM model

Revision ID: 337811a3f6b0
Revises: 5719f7612245
Create Date: 2020-07-18 18:01:48.205961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337811a3f6b0'
down_revision = '5719f7612245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # op.drop_column('users', 'fullname')
    # SQLite does not suport dropping columns (line above), work around below
    # https://stackoverflow.com/questions/30394222/why-flask-migrate-cannot-upgrade-when-drop-column
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('fullname')
