/**
 * Thumbnail Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PresignedUrl model module.
 * @module model/PresignedUrl
 * @version 1.0.0
 */
class PresignedUrl {
    /**
     * Constructs a new <code>PresignedUrl</code>.
     * @alias module:model/PresignedUrl
     * @param presignedUrl {String} 
     */
    constructor(presignedUrl) { 
        
        PresignedUrl.initialize(this, presignedUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, presignedUrl) { 
        obj['presigned_url'] = presignedUrl;
    }

    /**
     * Constructs a <code>PresignedUrl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PresignedUrl} obj Optional instance to populate.
     * @return {module:model/PresignedUrl} The populated <code>PresignedUrl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PresignedUrl();

            if (data.hasOwnProperty('presigned_url')) {
                obj['presigned_url'] = ApiClient.convertToType(data['presigned_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} presigned_url
 */
PresignedUrl.prototype['presigned_url'] = undefined;






export default PresignedUrl;

